# Generated by Django 2.2.12 on 2020-05-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apodo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=50)),
            ],
        ),
    ]
